### ISSUE TITLE
OpenMAINT not loading

### ISSUE THREAD

**Issue by jhill0111** [mrhavens/openmaint_docker#1]
Not sure if I'm doing something wrong. Following the instructions installs CMDBuild not OpenMAINT. Is there something else I need to do for OpenMAINT with empty database? Thank you in advance.

**Comment by mrhavens** [comment]
This version of OpenMAINT is a custom build that uses the CMDBuild code base. The OpenMAINT code base has issues and may not be properly maintained. Except for the name and database, the two applications are virtually identical.

**Comment by jhill0111** [comment]
Thanks for the reply. CMDBuild is open source for asset management. openMAINT is for Property & Facility Management. Is it possible to get openMAINT with an empty database? Thank you in advance.
